services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: prms-api
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: prms_projects
      CORS_ORIGIN: http://localhost:4200
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run start:dev

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: prms-web
    restart: unless-stopped
    ports:
      - '127.0.0.1:4250:4200'
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
    command: npm start

