services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    container_name: prms-api
    restart: unless-stopped
    env_file:
      - ./api/.env

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: production
    container_name: prms-web
    restart: unless-stopped
    ports:
      - '127.0.0.1:4250:80'
    depends_on:
      - api

